### ISSUE TITLE
Add option to narrow down list of OB selected

### ISSUE THREAD

**Issue by JeanBilheux** [ornlneutronimaging/rockit#7]
```
DataPath:
  ipts: 23788
ROI:
  mode: false
  xmax: null
  xmin: null
  ymax: null
  ymin: null
autoreduction: true
ob_auto_selection:
  days: 0
  hours: 3
  max_number_of_files: 12
  minutes: 0
  mode: true
  use_max_number_of_files: true
```
this is the config file to use
